spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
    context-path: /moviments