spring:
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
    context-path: /moviments