spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: finance_user
    password: 123456
    driverClassName: org.postgresql.Driver