spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: finance_user
    password: 123456
    driverClassName: org.postgresql.Driver
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
    context-path: /moviments