spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: update
    open-in-view: true
    
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
    context-path: /
logging:
  file:
    name: logs/monolith.log
  level:
    root: INFO