spring:
  profiles:
    active: prd
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
    context-path: /